joint_names:
  - kinova_joint_1
  - kinova_joint_2
  - kinova_joint_3
  - kinova_joint_4
  - kinova_joint_5
  - kinova_joint_6
  - kinova_joint_7
maximum_velocities:
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
maximum_accelerations:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 10.0
  - 10.0
  - 10.0
